---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    python_path: /usr/bin/python3.11

additional_build_steps:
  # Add this section to fix the pathing issue
  prepend_base:
    - ENV PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH

options:
  package_manager_path: /usr/bin/microdnf
